export const fileFilters = [
  { name: 'JavaScript Files', extensions: ['js', 'jsx', 'mjs', 'cjs'] },
  { name: 'TypeScript Files', extensions: ['ts', 'tsx'] },
  { name: 'Python Files', extensions: ['py', 'pyi', 'pyw', 'pyx', 'pxd', 'pxi', 'pyd'] },
  { name: 'Java Files', extensions: ['java', 'jav'] },
  { name: 'C/C++ Files', extensions: ['c', 'h', 'cpp', 'cc', 'cxx', 'hpp', 'hh', 'hxx'] },
  { name: 'C# Files', extensions: ['cs', 'csx'] },
  { name: 'HTML Files', extensions: ['html', 'htm', 'shtml', 'xhtml'] },
  { name: 'CSS Files', extensions: ['css', 'scss', 'sass', 'less'] },
  { name: 'JSON Files', extensions: ['json', 'jsonc', 'json5'] },
  { name: 'Markdown Files', extensions: ['md', 'markdown', 'mdown'] },
  { name: 'XML Files', extensions: ['xml', 'xsd', 'xsl', 'xslt'] },
  { name: 'YAML Files', extensions: ['yml', 'yaml'] },
  { name: 'Shell Scripts', extensions: ['sh', 'bash', 'zsh', 'fish', 'ksh'] },
  { name: 'PowerShell Files', extensions: ['ps1', 'psm1', 'psd1'] },
  { name: 'PHP Files', extensions: ['php', 'phtml', 'php3', 'php4', 'php5', 'php7', 'phps'] },
  { name: 'Ruby Files', extensions: ['rb', 'rbx', 'rjs', 'gemspec', 'rake', 'ru', 'erb'] },
  { name: 'Go Files', extensions: ['go'] },
  { name: 'Rust Files', extensions: ['rs', 'rlib'] },
  { name: 'Swift Files', extensions: ['swift'] },
  { name: 'Kotlin Files', extensions: ['kt', 'kts'] },
  { name: 'Scala Files', extensions: ['scala', 'sc'] },
  { name: 'R Files', extensions: ['r', 'rdata', 'rds', 'rda'] },
  { name: 'Dart Files', extensions: ['dart'] },
  { name: 'Lua Files', extensions: ['lua'] },
  { name: 'Perl Files', extensions: ['pl', 'pm', 'pod', 't'] },
  { name: 'SQL Files', extensions: ['sql', 'psql', 'plsql', 'mysql', 'sqlite'] },
  { name: 'GraphQL Files', extensions: ['graphql', 'gql'] },
  { name: 'Docker Files', extensions: ['dockerfile', 'dockerignore'] },
  { name: 'Git Files', extensions: ['gitignore'] },
  { name: 'Text Files', extensions: ['txt', 'text', 'log'] },
  { name: 'All Files', extensions: ['*'] }
]; 